Repository neildesa/Medical-Procedures-Map, pull requests merged in 2020-02, with the labels that each got.

#35 Update readme retrospective
  Sprint 1/Sprint_Retrospective/README.md
Labels: documentation

#36 Search the procedures based on min and max price
  Software_Code/JavaCode/JavaDatabaseCode/JavaFunctionsForJsp.java
  Software_Code/WebContent/index.jsp
Labels: enhancement

#37 Update README.md
  Sprint 1/README.md
Labels: documentation

#38 Added sprint 2 backlog
  Sprint 2/Sprint2_Backlog.xlsx
Labels: documentation

#39 Updated Product Backlog
  Product_Backlog/Backlog.xlsx
Labels: documentation

#40 Added the function button
  Software_Code/WebContent/Web/style.css
  Software_Code/WebContent/index.jsp
Labels: enhancement

#43 Added cost colours and rating placeholder
  Software_Code/WebContent/index.jsp
Labels: enhancement

#45 Haonan
  Software_Code/JavaCode/JavaDatabaseCodeTests/TestIsEmpty.java
  Software_Code/JavaCode/JavaDatabaseCodeTests/Test_JavaFuncForSQL.java
Labels: enhancement

#46 Added CSS animation
  Software_Code/WebContent/Web/style.css
Labels: enhancement

#48 Revert "Added some tests for functions in JavaFunctionsForJsp.java"
  .classpath
  .gitignore
  .project
  .settings/.jsdtscope
  .settings/org.eclipse.jdt.core.prefs
  .settings/org.eclipse.wst.common.component
  .settings/org.eclipse.wst.common.project.facet.core.xml
  .settings/org.eclipse.wst.jsdt.ui.superType.container
  .settings/org.eclipse.wst.jsdt.ui.superType.name
  Software_Code/JavaCode/JavaDatabaseCode/JavaFunctionsForJsp.java
  Software_Code/JavaCode/JavaDatabaseCodeTests/JavaFunctionsForJspTests.java
  Software_Code/JavaCode/JavaDatabaseCodeTests/test.java
  Software_Code/WebContent/index.jsp
  WebContent/META-INF/MANIFEST.MF
Labels: bug

#51 Added HTML form reload
  Software_Code/WebContent/index.jsp
Labels: enhancement

#53 New CSS animation
  Software_Code/WebContent/Web/style.css
Labels: enhancement

#54 added full tests for search procedure by distance
  Software_Code/JavaCode/JavaDatabaseCodeTests/Test_JavaFunctionsForJsp.java
Labels: enhancement

#55 new columns customer rating, IdDefinition
  Software_Code/JavaCode/JavaDatabaseCode/JavaFuncForSQL.java
  Software_Code/JavaCode/JavaDatabaseCode/MixData.java
  Software_Code/JavaCode/JavaDatabaseCode/ProcedureData.java
  Software_Code/JavaCode/JavaDatabaseCodeTests/TestJavaFuncForSQL.java
  Software_Code/JavaCode/JavaDatabaseCodeTests/Test_JavaFuncForSQL.java
Labels: enhancement

#56 Backlog from monday
  Sprint 2/Sprint_Backlog/Sprint2_Backlog-1.xlsx
Labels: documentation

#57 added the preparations for testing search by cost
  Software_Code/JavaCode/JavaDatabaseCode/JavaFunctionsForJsp.java
  Software_Code/JavaCode/JavaDatabaseCodeTests/Test_JavaFunctionsForJsp.java
Labels: bug

#58 Added Java Code for "GetSortByRating"
  Software_Code/JavaCode/JavaDatabaseCode/JavaFuncForSQL.java
Labels: enhancement

#59 Filter functionality
  Software_Code/JavaCode/JavaDatabaseCode/JavaFunctionsForJsp.java
  Software_Code/WebContent/details.jsp
  Software_Code/WebContent/index.jsp
Labels: enhancement

#60 Updated to add Rating
  Software_Code/JavaCode/JavaDatabaseCode/JavaFuncForSQL.java
Labels: enhancement

#61 Geocoding replaced by database lat/lng data
  Software_Code/WebContent/index.jsp
Labels: enhancement

#62 change package name for recognize them easier
  Software_Code/JavaCode/JavaDatabaseCodeTests/OutputTest_JavaFuncForSQL.java
  Software_Code/JavaCode/JavaDatabaseCodeTests/UnitTestJavaFuncForSQL.java
Labels: documentation

#63 Merged animations
  Software_Code/WebContent/Web/style.css
Labels: enhancement

#64 add some Junit test functions
  Software_Code/JavaCode/JavaDatabaseCode/JavaFuncForSQL.java
  Software_Code/JavaCode/JavaDatabaseCodeTests/OutputTest_JavaFuncForSQL.java
  Software_Code/JavaCode/JavaDatabaseCodeTests/UnitTestJavaFuncForSQL.java
Labels: testing

#65 Updated Product backlog for tuesday
  Product_Backlog/Backlog.xlsx
Labels: documentation

#66 changes of valuables
  Software_Code/JavaCode/JavaDatabaseCode/HospitalData.java
Labels: enhancement

#67 Updated sprint backlog for tuesday
  Sprint 2/Sprint_Backlog/Sprint2_Backlog-1.xlsx
Labels: documentation

#68 Cost rating tests
  Software_Code/JavaCode/JavaDatabaseCode/JavaFunctionsForJsp.java
  Software_Code/JavaCode/JavaDatabaseCodeTests/Test_JavaFunctionsForJsp.java
Labels: bug, testing

#69 Fixed Typo
  Sprint 2/README.md
Labels: documentation

#70 added method (and tests) to filter out distances above a certain range
  Software_Code/JavaCode/JavaDatabaseCode/Haversine.java
  Software_Code/JavaCode/JavaDatabaseCode/JavaFunctionsForJsp.java
  Software_Code/JavaCode/JavaDatabaseCodeTests/Test_JavaFunctionsForJsp.java
Labels: enhancement

#71 Added column animations
  Software_Code/WebContent/index.jsp
Labels: enhancement

#72 add some test code
  Software_Code/JavaCode/JavaDatabaseCode/JavaFuncForSQL.java
  Software_Code/JavaCode/JavaDatabaseCodeTests/OutputTest_JavaFuncForSQL.java
  Software_Code/JavaCode/JavaDatabaseCodeTests/UnitTestJavaFuncForSQL.java
Labels: testing

#73 Added colour to map markers
  Software_Code/WebContent/index.jsp
Labels: enhancement

#74 Home page
  Software_Code/JavaCode/JavaDatabaseCode/JavaFunctionsForJsp.java
  Software_Code/WebContent/Web/about.html
  Software_Code/WebContent/Web/index.html
  Software_Code/WebContent/details.jsp
  Software_Code/WebContent/index.jsp
  Software_Code/WebContent/resouces/home.jpg
Labels: enhancement

#75 Added sorting by distance Java function
  Software_Code/JavaCode/JavaDatabaseCode/JavaFunctionsForJsp.java
  Software_Code/JavaCode/JavaDatabaseCodeTests/Test_JavaFunctionsForJsp.java
Labels: enhancement

#76 Changed format of cost
  Software_Code/JavaCode/JavaDatabaseCode/JavaFunctionsForJsp.java
Labels: bug

#77 Added a price column to table
  Software_Code/WebContent/index.jsp
Labels: enhancement

#78 Distance test
  Software_Code/JavaCode/JavaDatabaseCode/JavaFunctionsForJsp.java
  Software_Code/JavaCode/JavaDatabaseCodeTests/Test_JavaFunctionsForJsp.java
  Software_Code/WebContent/Web/index.html
  Software_Code/WebContent/resources/home.jpg
Labels: enhancement, testing

#79 Updated sprint backlog for wednesday
  Sprint 2/Sprint_Backlog/Sprint2_Backlog-1.xlsx
Labels: documentation

#80 Get user Lat/Long in details.jsp
  Software_Code/WebContent/details.jsp
  Software_Code/WebContent/index.jsp
Labels: enhancement

#81 Table click behaviors
  Software_Code/WebContent/index.jsp
Labels: enhancement

#82 Html skip calls for sql
  Software_Code/JavaCode/JavaDatabaseCode/HTMLSkip.java
Labels: enhancement

#86 Sprint Retrospective documentation
  Sprint 2/Sprint_Retrospective/Sprint Retrospective Analysis.docx
Labels: documentation

#87 Integrates distance functionality
  Software_Code/JavaCode/JavaDatabaseCode/HTMLSkip.java
  Software_Code/JavaCode/JavaDatabaseCode/JavaFunctionsForJsp.java
  Software_Code/WebContent/details.jsp
  Software_Code/WebContent/index.jsp
Labels: enhancement

#88 Added rating back
  Software_Code/WebContent/index.jsp
Labels: bug

#91 Fixed 2 issues (see desc)
  Software_Code/JavaCode/JavaDatabaseCode/JavaFunctionsForJsp.java
  Software_Code/WebContent/details.jsp
Labels: bug

#92 Fixed sort
  Software_Code/JavaCode/JavaDatabaseCode/JavaFunctionsForJsp.java
Labels: bug

#93 More fixes
  Software_Code/JavaCode/JavaDatabaseCode/JavaFunctionsForJsp.java
  Software_Code/WebContent/details.jsp
  Software_Code/WebContent/index.jsp
Labels: bug, enhancement

#94 Refactored distance to use data from SQL
  Software_Code/WebContent/index.jsp
Labels: enhancement

#95 Min and Max cost slider
  Software_Code/WebContent/details.jsp
Labels: enhancement

#96 Changed default values
  Software_Code/WebContent/details.jsp
Labels: documentation

#97 Changed filter to sort
  Software_Code/WebContent/index.jsp
Labels: bug

#98 Sprint 2 Retrospective added to readme
  Sprint 2/Sprint_Retrospective/README.md
Labels: Documentation

#99 Update README.md
  Sprint 2/Sprint_Retrospective/README.md
Labels: Documentation

#100 Final product backlog
  Product_Backlog/Backlog.xlsx
Labels: Documentation
